### PR TITLE
Add props to control supported features and states

### PR DESCRIPTION
**Pull request by penn5**

### CODE REVIEW

**Comment by phhusson** [comment]
Please precise what issue does this fix.

**Comment by penn5** [comment]
Fixes https://github.com/phhusson/treble_experimentations/issues/376

**Comment by phhusson** [comment]
How would changing a timeout would fix a "command disallowed" answer thta comes instantly?

**Comment by penn5** [comment]
To be honest, I'm not sure. But it works. The way I found this is as follows:
1. Revert f8e8c59bcb6443651fdafbccbf24910cf84ed0fe
2. Install libbluetooth.so without the above commit
3. Get new logs
4. See that there is now a timeout in hci. 
5. Remove the abort() line from that timeout, just log it
6. See that bluetooth now functions normally, and the log shows that abort() would have been called due to a timeout in opcode 0x804
7. Try again without steps 1 and 2, see that it works (this is what I don't understand why)
8. Rather than removing abort() entirely in step 5, just ignore it if opcode is 0x804.
9. Bluetooth is still working
10. Change method to rather than ignore timeouts on 0x804, just increase the timeout.

You can check what's going on by activating HCI Snoop Logging in developer options and getting the log. Its a standard pcap, load it into wireshark to read it. If you filter in wireshark for "bthci_cmd.opcode == 0x804" you can see that about half the time, the command to response delta is <2000ms and half the time it's above. Since the timeout is 2000ms, this means that that command crashes the HCI stack half of the time.

**Comment by penn5** [comment]
Tested, I got a 2464ms timeout on 0x804 and no bluetooth interrupt with just this patch.

**Comment by DaveidWeba** [comment]
This is going to sound like a dumb question, but how can I test the effectiveness of this patch on my device (Mate SE/Honor 7x)? I would love to be a guinea pig! If a .zip can be provided with already compiled files, I'll flash it ASAP.

**Comment by penn5** [comment]
Not a zip as such, but I can send you the libbluetoothservice.so? Check your telegram.

> This is going to sound like a dumb question, but how can I test the effectiveness of this patch on my device (Mate SE/Honor 7x)? I would love to be a guinea pig! If a .zip can be provided with already compiled files, I'll flash it ASAP.

**Comment by penn5** [comment]
Some users have found that the first patch does not complete the fix. This should fix that.

**Comment by DaveidWeba** [comment]
@phhusson I can confirm this fixes a few problems I was previously having with bluetooth! After replacing the libbluetooth.so files in /system/lib/ and /system/lib64/ I can now connect to my smart band, the Honor Band 4, and extract sleep data & receive real-time notifications on my band. Connecting to stereo headsets is working fine too, I will run an extensive test with music soon to make sure it doesn't disconnect after 30+ minutes of streaming.

photo_2019-02-09_13-21-29
photo_2019-02-09_13-16-00 2
photo_2019-02-09_13-16-00

**Comment by penn5** [comment]
@DaveidWeba has confirmed after the latest patch his issue is resolved (although it syncs slowly). My issue is also resolved after latest patch.

**Comment by penn5** [comment]
Some people are reporting still getting connection failures after this latest patch. I believe that it's an app bug as https://stackoverflow.com/questions/52000776/ble-device-stops-connecting-with-android-after-working-flawlessly-for-weeks reported it as being caused by spammy connections on a stock ROM. I think a factory reset would fix it, I'm checking now.

**Comment by Sparticuz** [comment]
I'd also like to try this out on my Mate SE. Can't connect to my Garmin vivo fitness tracker. Bluetooth just constantly crashes when trying to pair it. Which channel in telegram are you on so I can grab that .so file also? (Is it built for 110 or 109, or will it matter?)

**Comment by penn5** [comment]
This new version is more generic, should be able to fix https://github.com/phhusson/treble_experimentations/issues/399 as well as https://github.com/phhusson/treble_experimentations/issues/376

**Comment by penn5** [comment]
setprop persist.sys.bt.unsupport.features 00000001
setprop persist.sys.bt.unsupport.states 000000000000000000000011111
to fix https://github.com/phhusson/treble_experimentations/issues/376 after the new version of the patch

**Comment by DeinzerP** [comment]
Hi, i would love to fix my Bluetooth issue, https://github.com/phhusson/treble_experimentations/issues/376 but i can't understand what i should do, since i am not a Android dev. Is it possible to provide this fix in form of a flashable ZIP, or at least an easy to understand instruction with the required files included? I would really appreciate that, Thanks.

**Pull request merged**
