### PR TITLE
Add bitmask for mt6797 too (supported features)

### PR DESCRIPTION
**Pull request by penn5**
Standard features as well as extended features
This is not tested because I don't have enough storage. Perhaps you could test for me before merging (fi @dil3mm4)? It's a simple copy of #1 because I forgot to add the normal features and only did extended features.

### CODE REVIEW

**Comment by phhusson** [comment]
K noted.
I'll rewrite it, please remind me of it.
What's the feature not supported on mt6797?

**Comment by penn5** [comment]
https://github.com/phhusson/treble_experimentations/issues/399, needed bitmask is `persist.sys.bt.unsupport.stdfeatures=000001`

**Comment by penn5** [comment]
@phhusson reminding you of it day after release day...

**Comment by penn5** [comment]
Merged https://github.com/phhusson/platform_system_bt/commit/726ea538e933b77daa86537ca7b376bbb78aa9f8

**Pull request closed without merging**
